- hosts: localhost
  vars:
    sample_vars: ansible_test
  tasks:
    - shell: uptime
      register: result

    - debug:
        msg: "{{ result.stdout }}"
    
    - debug:
        msg: "{{ sample_vars }}"

    - debug:
        msg: "{{ ansible_env.PWD }}"

    - name: "Base packages"
      apt:
        pkg:
          - git
          - vim
          - language-pack-ja
          - fish
          - docker.io
          - gcc
          - make
          - golang
          - jq
          - zlib1g-dev
          - libssl-dev
          - unzip
          - libffi-dev
          - prometheus-node-exporter
        state: present
        update_cache: yes

    - name: "Install n for nodejs"
      shell: |
        if type n > /dev/null; then
          echo "n package already installed."
        else
          sudo apt-get install nodejs npm -y
          sudo npm install -g n
          sudo n lts
          sudo apt-get purge nodejs npm -y
        fi
      register: result_install_n

    - name: "Install pyenv"
      shell: |
        if [ ! -f "${HOME}/.pyenv/bin/pyenv" ]; then
          curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
        fi

    - debug:
        msg: "{{ result_install_n }}"


