- hosts: localhost
  vars:
    sample_vars: ansible_test
  tasks:
    - shell: uptime
      register: result

    - debug:
        msg: "{{ result.stdout }}"
    
    - debug:
        msg: "{{ sample_vars }}"

    - debug:
        msg: "{{ ansible_env.PWD }}"

    - name: "Base packages"
      apt:
        pkg:
          - git
          - vim
          - language-pack-ja
          - fish
          - docker.io
          - gcc
          - make
          - golang
          - prometheus-node-exporter
        state: present
        update_cache: yes

    - name: "Install n for nodejs"
      shell: |
        sudo apt-get install nodejs npm -y
        sudo npm install -g n
        sudo n lts
        sudo apt-get purge nodejs npm -y
      register: result_install_n

    - debug:
        msg: "{{ result_install_n }}"


